TRUNCATE TABLE presidents;
TRUNCATE TABLE vice_presidents;

ALTER SEQUENCE presidents_id_seq RESTART WITH 1;
ALTER SEQUENCE vice_presidents_id_seq RESTART WITH 1;

INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('George Washington', 'None', 1789, False, 1);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('John Adams', 'Federalist', 1796, False, 2);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Thomas Jefferson', 'Democratic-Republican', 1800, False, 3);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('James Madison', 'Democratic-Republican', 1808, False, 4);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('James Monroe', 'Democratic-Republican', 1816, False, 5);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('John Quincy Adams', 'Democratic-Republican', 1824, False, 6);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Andrew Jackson', 'Democratic', 1828, False, 7);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Martin Van Buren', 'Democratic', 1836, False, 8);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('William Henry Harrison', 'Whig', 1840, False, 9);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('John Tyler', 'Whig', 1841, False, 10);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('James K. Polk', 'Democratic', 1844, False, 11);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Zachary Taylor', 'Whig', 1848, False, 12);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Millard Fillmore', 'Whig', 1850, False, 13);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Franklin Pierce', 'Democratic', 1852, False, 14);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('James Buchanan', 'Democratic', 1856, False, 15);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Abraham Lincoln', 'Republican', 1860, False, 16);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Andrew Johnson', 'Democratic', 1865, False, 17);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Ulysses S. Grant', 'Republican', 1868, False, 18);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Rutherford B. Hayes', 'Republican', 1876, False, 19);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('James A. Garfield', 'Republican', 1880, False, 20);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Chester A. Arthur', 'Republican', 1881, False, 21);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Grover Cleveland', 'Democratic', 1884, False, 22);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Benjamin Harrison', 'Republican', 1888, False, 23);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Grover Cleveland', 'Democratic', 1892, False, 24);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('William McKinley', 'Republican', 1896, False, 25);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Theodore Roosevelt', 'Republican', 1901, False, 26);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('William Howard Taft', 'Republican', 1908, False, 27);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Woodrow Wilson', 'Democratic', 1912, False, 28);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Warren G. Harding', 'Republican', 1920, False, 29);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Calvin Coolidge', 'Republican', 1923, False, 30);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Herbert Hoover', 'Republican', 1928, False, 31);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Franklin D. Roosevelt', 'Democratic', 1932, False, 32);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Harry S. Truman', 'Democratic', 1945, False, 33);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Dwight D. Eisenhower', 'Republican', 1952, False, 34);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('John F. Kennedy', 'Democratic', 1960, False, 35);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Lyndon B. Johnson', 'Democratic', 1963, False, 36);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Richard Nixon', 'Republican', 1968, False, 37);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Gerald Ford', 'Republican', 1974, False, 38);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Jimmy Carter', 'Democratic', 1976, True, 39);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Ronald Reagan', 'Republican', 1980, False, 40);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('George H. W. Bush', 'Republican', 1988, False, 41);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Bill Clinton', 'Democratic', 1992, True, 42);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('George W. Bush', 'Republican', 2000, True, 43);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Barack Obama', 'Democratic', 2008, True, 44);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Donald Trump', 'Republican', 2016, True, 45);
INSERT INTO presidents(name, party, year_elected, is_alive, vice_president_id) VALUES ('Joe Biden', 'Democratic', 2020, False, 46);
